import { Close } from "@mui/icons-material";
import { Dialog, DialogContent, DialogTitle, IconButton, Link, Stack, Tab, Tabs, Typography, useTheme } from "@mui/material";

function CreditsModal({ open, setCredits }) {
  const theme = useTheme();



  return (
    <Dialog
      fullWidth
      maxWidth='sm'
      className="backdrop-blur"
      sx={{ background: 'transparent !important', '& .MuiDialog-paper': { borderRadius: 0, background: `${theme.palette.primary.main} !important`, backdropFilter: 'blur(10px)' } }}
      open={open}
      onClose={() => setCredits(false)}
    >
      <DialogTitle className="backdrop-blur" sx={{ background: 'transparent !important' }} color="primary">
        <Stack direction={'row'} alignItems={"center"} justifyContent={"space-between"}>
          <Typography variant="h6" color="secondary">Credits</Typography>
          <IconButton onClick={() => setCredits(false)} color="secondary"><Close /></IconButton>
        </Stack>
      </DialogTitle>
      <DialogContent className="backdrop-blur" sx={{ background: 'transparent' }}>
        <Stack spacing={2}>
          <div>
            <img src="/cef_logo.png" width="100%" />
          </div>

          <Typography color="selected" fontWeight="bold">
            CEF Telecom project 2018-EU-IA-0095. This project is co-financed by the European Union.
          </Typography>



          <Typography color="secondary" fontSize={'12px'}>
            This work has also received funding from the European Union's Horizon Europe research and innovation programme under grant agreement No. 101059548.
          </Typography>


          <Typography color="secondary" fontSize={'12px'}>
            Open Environmental Data Cube is based on open-source software: Geoserver, Geonetwork, React, GDAL, OpenLayers and many others. Predictions are based on python and R packages software for statistical modeling, machine learning and spatial analysis: sci-kit learn, tensorflow, rasterio, mlr and terra. Spatial analysis and visualization was implemented using: GDAL, SAGA GIS, GRASS GIS, QGIS and WhiteBoxTools.
          </Typography>

          <Typography color="secondary" fontSize={'12px'}>
            We are grateful to the <Link color="selected" fontWeight="bold" href="https://gilab.rs">GiLAB Ltd</Link> for back-end and front-end development of the App. We are also grateful to European Commission Joint Research Centre for providing support with data preprocessing and interpretation of results.
          </Typography>


          <Typography color="secondary" fontSize={'12px'}>
            Background layers include:
            <ul>
              <li><Link href="https://www.openstreetmap.org/" color="selected" fontWeight="bold"> OpenStreetMap</Link> © OpenStreetMap contributors</li>
              <li><Link href="https://opentopomap.org/" color="selected" fontWeight="bold"> OpenTopoMap</Link> cartography © OpenTopoMap</li>
              <li><Link href="https://www.bing.com/maps/aerial" color="selected" fontWeight="bold"> BingMaps Aerial</Link> © 2018 Microsoft</li>
            </ul>


          </Typography>

          <Typography color="secondary" fontSize={'12px'}>
            Landsat ARD images were obtained from the <Link color="selected" fontWeight="bold" href="https://glad.umd.edu/">Global Land Analysis and Discovery</Link> (GLAD), courtesy of University of Maryland. For more information about the Landsat ARD repository at GLAD please refer to <Link color="selected" fontWeight="bold" href="https://www.mdpi.com/2072-4292/12/3/426">Potapov et al. (2020)</Link>.
          </Typography>

          <Typography color="secondary" fontSize={'12px'}>
            Training points Land cover classes were prepared by CVUT Prague from a combination of the <Link color="selected" fontWeight="bold" href="https://land.copernicus.eu/imagery-in-situ/lucas">LUCAS survey points</Link> (<Link color="selected" fontWeight="bold" href="https://doi.org/10.1111/ejss.12499">Orgiazzi et al., 2018; </Link><Link color="selected" fontWeight="bold" href="https://doi.org/10.1038/s41597-020-00675-z">d’Andrimont et al., 2020</Link>) and points generated from the CORINE land cover maps.
          </Typography>


          <Typography color="secondary" fontSize={'12px'}>
            Training points Forest tree species were generated by combining a number of data sets including the <Link color="selected" fontWeight="bold" href="https://www.gbif.org/occurrence/search">GBIF occurrences</Link>, EU forest dataset (<Link color="selected" fontWeight="bold" href="https://doi.org/10.1038/sdata.2016.123">Mauri et al., 2017</Link>) and similar. The preprocessing steps are documented in detail in the OpenLandMap.org repository by <Link href="https://www.uni-muenster.de/Geoinformatics/en/institute/staff/index.php/354/Johannes_Heisig" color="selected" fontWeight={'bold'}>Johannes Heisig</Link>.
          </Typography>

          <Typography color="secondary" fontSize={'12px'}>
            CORINE Land Cover layers 2000, 2006, 2012, 2018 were obtained from the <Link color="selected" fontWeight="bold" href="https://land.copernicus.eu/">Copernicus Land Monitoring Service</Link> (100m - <Link href="https://elib.dlr.de/113171/" color="selected" fontWeight="bold">Moser et al., 2017</Link>). CORINE layers were produced by The Eionet network National Reference Centres Land Cover (NRC/LC).
          </Typography>

          <Typography color="secondary" fontSize={'12px'} fontStyle={'italic'}>
            Cited sources:
          </Typography>
          <ol>
  <li style={{ color: '#fff' }}>
    <Typography color="secondary" fontSize={'12px'} fontStyle={'italic'}>
      d’Andrimont, R., Yordanov, M., Martinez-Sanchez, L. et al. Harmonised LUCAS in-situ land cover and use database for field surveys from 2006 to 2018 in the European Union. Sci Data 7, 352 (2020). <Link color="selected" fontWeight="bold" href="https://doi.org/10.1038/s41597-020-00675-z">https://doi.org/10.1038/s41597-020-00675-z</Link>
    </Typography>
  </li>
  <li style={{ color: '#fff' }}>
    <Typography color="secondary" fontSize={'12px'} fontStyle={'italic'}>
      Mauri, A., Strona, G., & San-Miguel-Ayanz, J. (2017). EU-Forest, a high-resolution tree occurrence dataset for Europe. Scientific data, 4(1), 1-8. <Link color="selected" fontWeight="bold" href="https://doi.org/10.1038/sdata.2016.123">https://doi.org/10.1038/sdata.2016.123</Link>
    </Typography>
  </li>
  <li style={{ color: '#fff' }}>
    <Typography color="secondary" fontSize={'12px'} fontStyle={'italic'}>
      Moser, Linda and Probeck, Markus and Ramminger, Gernot and Sannier, Christophe and Desclée, Baudouin and Schardt, Matthias and Gallaun, Heinz and Deutscher, Janik and Defourny, Pierre and Blaes, Xavier and Klein, Igor and Keil, Manfred and Hirner, Andreas and Esch, Thomas (2017) Sentinel-based Evolution of Copernicus Land Services on Continental and Global Scale. WorldCover 2017, 14–16 March 2017, Frascati (Rome), Italy. <Link color="selected" fontWeight="bold" href="https://elib.dlr.de/113171/">https://elib.dlr.de/113171/</Link>
    </Typography>
  </li>
  <li style={{ color: '#fff' }}>
    <Typography color="secondary" fontSize={'12px'} fontStyle={'italic'}>
      Orgiazzi, A., Ballabio, C., Panagos, P., Jones, A., & Fernández‐Ugalde, O. (2018). LUCAS Soil, the largest expandable soil dataset for Europe: a review. European Journal of Soil Science, 69(1), 140-153. <Link color="selected" fontWeight="bold" href="https://doi.org/10.1111/ejss.12499">https://doi.org/10.1111/ejss.12499</Link>
    </Typography>
  </li>
  <li style={{ color: '#fff' }}>
    <Typography color="secondary" fontSize={'12px'} fontStyle={'italic'}>
      Potapov P., Hansen M.C., Kommareddy I., Kommareddy A., Turubanova S., Pickens A., Adusei B., Tyukavina A., Ying Q., (2020). Landsat Analysis Ready Data for Global Land Cover and Land Cover Change Mapping. Remote Sensing, 12(3):426. <Link color="selected" fontWeight="bold" href="https://doi.org/10.3390/rs12030426">https://doi.org/10.3390/rs12030426</Link>
    </Typography>
  </li>
  <li style={{ color: '#fff' }}>
    <Typography color="secondary" fontSize={'12px'} fontStyle={'italic'}>
      Witjes, M., Leal Parente, L., Krizan, J., Antonic, L., Hengl, T. (2023). Ecodatacube.eu: Analysis-ready open environmental data cube for Europe. PeerJ, <Link color="selected" fontWeight="bold" href="https://doi.org/10.21203/rs.3.rs-2277090/v4">https://doi.org/10.21203/rs.3.rs-2277090/v4</Link>
    </Typography>
  </li>
</ol>

        </Stack>

      </DialogContent>
    </Dialog>
  );
}

export default CreditsModal;