export const initState = {
  _3D: false,
  sidebar: true,
  base: 'osm_gray',
  vector: 'nuts',
	layer: "CORINE Land Cover (CLC+) Backbone",
  layer2: 'AI4SoilHealth: Soil type dominant class-2',
  time: '20200101_20221231',
  time2: '.vitric.andosols',
  depth: '0cm',
  depth2: '0cm',
	opacity: 45,
	zoom: 4,
	center: [17.0066, 53.7139],
	geolocation: false,
  tab: 'mastodon',
  loading: true,
  comparison: false,
}